
name: Build And Upload Artifact

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Grant execute permission to gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Delete -dev and -sources
        run: rm -rf build/libs/*-sources.jar build/libs/*-dev.jar

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Compiled artifacts for ${{ github.sha }}
          path: build/libs
